# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5958e2ee4d2debd1c79c0abf94a22a874d83baaf993d047da2b2bfe989549c2a2c6b904d35c0738df785881e6797ba73192d71bdfb0753eadda82967e4211415

test:
  secret_key_base: f42bdf67d3d444049c4fa360e97da070883e79a4847c9b3be7bc2943b5ad81a4baa32b637672307705f535f033c5baac3848c62f585302ce8250632f53f7bcf2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
